class Tutorial {
  final int id;
  final String name,
      visual,
      teacher,
      difficulty,
      type,
      musicname,
      singer,
      caption;
  final List<String> style;

  Tutorial({
    this.id,
    this.visual,
    this.name,
    this.style,
    this.teacher,
    this.difficulty,
    this.musicname,
    this.singer,
    this.type,
    this.caption,
  });
}

List<Tutorial> tutorials = [
  Tutorial(
    id: 1,
    name: "Anyone dance tutorial",
    style: ["Commercial", "Street jazz"],
    visual: "assets/images/aliya_anyone.jpg",
    teacher: "Aliya",
    difficulty: "intermediate",
    musicname: "Anyone",
    singer: "Justin Bieber",
    type: "Choreography",
    caption:
        "You were waiting for Aliya's tutorial here it is! Grab your heels and enjoy the class!",
  ),
  Tutorial(
    id: 2,
    name: "Amnesia dance tutorial",
    style: ["Commercial", "Hip-Hop"],
    visual: "assets/images/bam_amnesia.jpg",
    teacher: "Bam Martin",
    difficulty: "Advanced",
    musicname: "Amnesia",
    singer: "The big hash",
    type: "Choreography",
    caption:
        "You were waiting for Bim's new tutorial here it is! Warm up and enjoy the class!",
  ),
  Tutorial(
    id: 3,
    name: "Waves tutorial",
    style: ["Popping"],
    visual: "assets/images/boogie_waves.jpg",
    teacher: "Boogie Franky",
    difficulty: "Begginer",
    musicname: "Shot Down",
    singer: "DJ BX",
    type: "Routine",
    caption:
        "A good dancer must have strong foundations, here are some basics to level up your game!",
  ),
  Tutorial(
    id: 4,
    name: "Easy dance tutorial",
    style: ["Commercial", "Hip-Hop"],
    visual: "assets/images/cj.easy.jpg",
    teacher: "Cj Salvador",
    difficulty: "Intermediate",
    musicname: "Easy",
    singer: "Dani Leigh",
    type: "Choreography",
    caption:
        "You were waiting for Cj's tutorial here it is! Grab your sneakers and enjoy the class!",
  ),
  Tutorial(
    id: 5,
    name: "Heat dance tutorial",
    style: ["Commercial", "Hip-Hop"],
    visual: "assets/images/cj.heat.jpg",
    teacher: "Cj Salvador",
    difficulty: "Advanced",
    musicname: "Heat",
    singer: "Chris Brown",
    type: "Choreography",
    caption:
        "You were waiting for Cj's tutorial here it is! Grab your sneakers and enjoy the class!",
  ),
  Tutorial(
    id: 6,
    name: "Get together dance tutorial",
    style: ["Commercial", "House"],
    visual: "assets/images/jardy.gettogether.jpg",
    teacher: "Jardy",
    difficulty: "Intermediate",
    musicname: "Get together",
    singer: "Drake",
    type: "Choreography",
    caption:
        "You were waiting for Jardy's tutorial here it is! Grab your sneakers and enjoy the class!",
  ),
  Tutorial(
    id: 7,
    name: "Loose leg tutorial",
    style: ["House"],
    visual: "assets/images/joj_looseleg.jpg",
    teacher: "JoJo",
    difficulty: "Begginer",
    musicname: "I loved you",
    singer: "Kerrie Chandeler",
    type: "Routine",
    caption:
        "A good dancer must have strong foundations, here are some basics to level up your game!",
  ),
  Tutorial(
    id: 8,
    name: "Foundations tutorial",
    style: ["House"],
    visual: "assets/images/jojo_foundations.jpg",
    teacher: "JoJo",
    difficulty: "Intermediate",
    musicname: "I need you",
    singer: "Kerrie Chandeler",
    type: "Routine",
    caption:
        "A good dancer must have strong fundations, here are some basics to level up your game!",
  ),
  Tutorial(
    id: 9,
    name: "Fresno tutorial",
    style: ["Popping"],
    visual: "assets/images/kidboogie_fresno.jpg",
    teacher: "Kid Boogie",
    difficulty: "Begginer",
    musicname: "Fu-Gee-La",
    singer: "DJ BX",
    type: "Routine",
    caption:
        "A good dancer must have strong foundations, here are some basics to level up your game!",
  ),
  Tutorial(
    id: 10,
    name: "Walk out tutorial",
    style: ["Popping"],
    visual: "assets/images/kidboogie_walk.jpg",
    teacher: "Kid Boogie",
    difficulty: "Begginer",
    musicname: "Go Teti Up Get DJ",
    singer: "DJ BX",
    type: "Routine",
    caption:
        "A good dancer must have strong foundations, here are some basics to level up your game!",
  ),
  Tutorial(
    id: 11,
    name: "Ratchet dance tutorial",
    style: ["Commercial", "Street jazz"],
    visual: "assets/images/kiira_ratched.jpg",
    teacher: "Kiira",
    difficulty: "Advanced",
    musicname: "Ratchet",
    singer: "Megan",
    type: "Choreography",
    caption:
        "You were waiting for Kiira's tutorial here it is! Grab your heels and enjoy the class!",
  ),
  Tutorial(
    id: 12,
    name: "Drop dance tutorial",
    style: ["Commercial", "Hip-Hop"],
    visual: "assets/images/scott_drop.jpg",
    teacher: "Scott Forsyth",
    difficulty: "Advanced",
    musicname: "Drop",
    singer: "Timbaland",
    type: "Choreography",
    caption:
        "You were waiting for Cj's tutorial here it is! Grab your sneakers and enjoy the class!",
  ),
];
